import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import ReactQueryProvider from '@/providers/ReactQueryProvider';

import { SideBar } from '@/components/SideBar';

import './globals.css';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <SideBar />
        <div className="main-container">
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </div>
      </body>
    </html>
  );
}
